org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.218
loader_version_range=[1,)
journeymap_api_version=2.0.0-1.21.1-SNAPSHOT

mod_id=findanyway
mod_name=FindAnyway
mod_license=MIT
mod_version=0.1.0
mod_group_id=de.gener.findanyway
mod_authors=Gener
mod_description=Client-only biome and structure finder for already loaded chunks.
